### ISSUE TITLE
Reading from socket

### ISSUE THREAD

**Issue by Johnathon332** [britram/python-ipfix#19]
I have netflow traffic pointed to my device and want to listen on a specific port for netflow, does v9pdu support reading from sockets for netflow data and then parsing it?  If so how would I go about doing this?

**Comment by britram** [comment]
Nope, no support for reading v9pdus from a socket, since all the V9 stuff here is basically a hack for a specific V9 dataset (which I haven't had anything to do with for a few years, hence my inactivity in this repo).

It should be possible to write a quick UDP collector that creates a new PduBuffer from an  mbuf  initialized with the content of a v9 PDU received from a UDP socket; not having any V9 exporters, though, I couldn't test such a think.

PRs enthusiastically accepted.
